/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComandosRouteImport } from './routes/comandos'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as AuthenticatedDashboardGuildIdRouteImport } from './routes/_authenticated/dashboard.$guildId'
import { Route as AuthenticatedAdminPremiumRouteImport } from './routes/_authenticated/admin.premium'
import { Route as AuthenticatedDashboardGuildIdIndexRouteImport } from './routes/_authenticated/dashboard.$guildId.index'
import { Route as ApiAuthDiscordLoginRouteImport } from './routes/api/auth/discord/login'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'
import { Route as AuthenticatedDashboardGuildIdWelcomeRouteImport } from './routes/_authenticated/dashboard.$guildId.welcome'
import { Route as AuthenticatedDashboardGuildIdTicketsRouteImport } from './routes/_authenticated/dashboard.$guildId.tickets'
import { Route as AuthenticatedDashboardGuildIdSocialRouteImport } from './routes/_authenticated/dashboard.$guildId.social'
import { Route as AuthenticatedDashboardGuildIdSeasonsRouteImport } from './routes/_authenticated/dashboard.$guildId.seasons'
import { Route as AuthenticatedDashboardGuildIdReactionRolesRouteImport } from './routes/_authenticated/dashboard.$guildId.reaction-roles'
import { Route as AuthenticatedDashboardGuildIdPremiumRouteImport } from './routes/_authenticated/dashboard.$guildId.premium'
import { Route as AuthenticatedDashboardGuildIdPermissoesRouteImport } from './routes/_authenticated/dashboard.$guildId.permissoes'
import { Route as AuthenticatedDashboardGuildIdModerationRouteImport } from './routes/_authenticated/dashboard.$guildId.moderation'
import { Route as AuthenticatedDashboardGuildIdLogsRouteImport } from './routes/_authenticated/dashboard.$guildId.logs'
import { Route as AuthenticatedDashboardGuildIdLevelingRouteImport } from './routes/_authenticated/dashboard.$guildId.leveling'
import { Route as AuthenticatedDashboardGuildIdEmbedsRouteImport } from './routes/_authenticated/dashboard.$guildId.embeds'
import { Route as AuthenticatedDashboardGuildIdEconomyRouteImport } from './routes/_authenticated/dashboard.$guildId.economy'
import { Route as AuthenticatedDashboardGuildIdCommunityRouteImport } from './routes/_authenticated/dashboard.$guildId.community'
import { Route as AuthenticatedDashboardGuildIdCommandsRouteImport } from './routes/_authenticated/dashboard.$guildId.commands'
import { Route as AuthenticatedDashboardGuildIdBadgesRouteImport } from './routes/_authenticated/dashboard.$guildId.badges'
import { Route as AuthenticatedDashboardGuildIdAutoroleRouteImport } from './routes/_authenticated/dashboard.$guildId.autorole'
import { Route as AuthenticatedDashboardGuildIdAutomodRouteImport } from './routes/_authenticated/dashboard.$guildId.automod'
import { Route as AuthenticatedDashboardGuildIdAchievementsRouteImport } from './routes/_authenticated/dashboard.$guildId.achievements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandosRoute = ComandosRouteImport.update({
  id: '/comandos',
  path: '/comandos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardGuildIdRoute =
  AuthenticatedDashboardGuildIdRouteImport.update({
    id: '/dashboard/$guildId',
    path: '/dashboard/$guildId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPremiumRoute =
  AuthenticatedAdminPremiumRouteImport.update({
    id: '/admin/premium',
    path: '/admin/premium',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardGuildIdIndexRoute =
  AuthenticatedDashboardGuildIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const ApiAuthDiscordLoginRoute = ApiAuthDiscordLoginRouteImport.update({
  id: '/api/auth/discord/login',
  path: '/api/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardGuildIdWelcomeRoute =
  AuthenticatedDashboardGuildIdWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdTicketsRoute =
  AuthenticatedDashboardGuildIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdSocialRoute =
  AuthenticatedDashboardGuildIdSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdSeasonsRoute =
  AuthenticatedDashboardGuildIdSeasonsRouteImport.update({
    id: '/seasons',
    path: '/seasons',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdReactionRolesRoute =
  AuthenticatedDashboardGuildIdReactionRolesRouteImport.update({
    id: '/reaction-roles',
    path: '/reaction-roles',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdPremiumRoute =
  AuthenticatedDashboardGuildIdPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdPermissoesRoute =
  AuthenticatedDashboardGuildIdPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdModerationRoute =
  AuthenticatedDashboardGuildIdModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdLogsRoute =
  AuthenticatedDashboardGuildIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdLevelingRoute =
  AuthenticatedDashboardGuildIdLevelingRouteImport.update({
    id: '/leveling',
    path: '/leveling',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdEmbedsRoute =
  AuthenticatedDashboardGuildIdEmbedsRouteImport.update({
    id: '/embeds',
    path: '/embeds',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdEconomyRoute =
  AuthenticatedDashboardGuildIdEconomyRouteImport.update({
    id: '/economy',
    path: '/economy',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdCommunityRoute =
  AuthenticatedDashboardGuildIdCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdCommandsRoute =
  AuthenticatedDashboardGuildIdCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdBadgesRoute =
  AuthenticatedDashboardGuildIdBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdAutoroleRoute =
  AuthenticatedDashboardGuildIdAutoroleRouteImport.update({
    id: '/autorole',
    path: '/autorole',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdAutomodRoute =
  AuthenticatedDashboardGuildIdAutomodRouteImport.update({
    id: '/automod',
    path: '/automod',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdAchievementsRoute =
  AuthenticatedDashboardGuildIdAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comandos': typeof ComandosRoute
  '/login': typeof LoginRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$guildId/achievements': typeof AuthenticatedDashboardGuildIdAchievementsRoute
  '/dashboard/$guildId/automod': typeof AuthenticatedDashboardGuildIdAutomodRoute
  '/dashboard/$guildId/autorole': typeof AuthenticatedDashboardGuildIdAutoroleRoute
  '/dashboard/$guildId/badges': typeof AuthenticatedDashboardGuildIdBadgesRoute
  '/dashboard/$guildId/commands': typeof AuthenticatedDashboardGuildIdCommandsRoute
  '/dashboard/$guildId/community': typeof AuthenticatedDashboardGuildIdCommunityRoute
  '/dashboard/$guildId/economy': typeof AuthenticatedDashboardGuildIdEconomyRoute
  '/dashboard/$guildId/embeds': typeof AuthenticatedDashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/leveling': typeof AuthenticatedDashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logs': typeof AuthenticatedDashboardGuildIdLogsRoute
  '/dashboard/$guildId/moderation': typeof AuthenticatedDashboardGuildIdModerationRoute
  '/dashboard/$guildId/permissoes': typeof AuthenticatedDashboardGuildIdPermissoesRoute
  '/dashboard/$guildId/premium': typeof AuthenticatedDashboardGuildIdPremiumRoute
  '/dashboard/$guildId/reaction-roles': typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  '/dashboard/$guildId/seasons': typeof AuthenticatedDashboardGuildIdSeasonsRoute
  '/dashboard/$guildId/social': typeof AuthenticatedDashboardGuildIdSocialRoute
  '/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/dashboard/$guildId/': typeof AuthenticatedDashboardGuildIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comandos': typeof ComandosRoute
  '/login': typeof LoginRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$guildId/achievements': typeof AuthenticatedDashboardGuildIdAchievementsRoute
  '/dashboard/$guildId/automod': typeof AuthenticatedDashboardGuildIdAutomodRoute
  '/dashboard/$guildId/autorole': typeof AuthenticatedDashboardGuildIdAutoroleRoute
  '/dashboard/$guildId/badges': typeof AuthenticatedDashboardGuildIdBadgesRoute
  '/dashboard/$guildId/commands': typeof AuthenticatedDashboardGuildIdCommandsRoute
  '/dashboard/$guildId/community': typeof AuthenticatedDashboardGuildIdCommunityRoute
  '/dashboard/$guildId/economy': typeof AuthenticatedDashboardGuildIdEconomyRoute
  '/dashboard/$guildId/embeds': typeof AuthenticatedDashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/leveling': typeof AuthenticatedDashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logs': typeof AuthenticatedDashboardGuildIdLogsRoute
  '/dashboard/$guildId/moderation': typeof AuthenticatedDashboardGuildIdModerationRoute
  '/dashboard/$guildId/permissoes': typeof AuthenticatedDashboardGuildIdPermissoesRoute
  '/dashboard/$guildId/premium': typeof AuthenticatedDashboardGuildIdPremiumRoute
  '/dashboard/$guildId/reaction-roles': typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  '/dashboard/$guildId/seasons': typeof AuthenticatedDashboardGuildIdSeasonsRoute
  '/dashboard/$guildId/social': typeof AuthenticatedDashboardGuildIdSocialRoute
  '/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/comandos': typeof ComandosRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/_authenticated/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/$guildId/achievements': typeof AuthenticatedDashboardGuildIdAchievementsRoute
  '/_authenticated/dashboard/$guildId/automod': typeof AuthenticatedDashboardGuildIdAutomodRoute
  '/_authenticated/dashboard/$guildId/autorole': typeof AuthenticatedDashboardGuildIdAutoroleRoute
  '/_authenticated/dashboard/$guildId/badges': typeof AuthenticatedDashboardGuildIdBadgesRoute
  '/_authenticated/dashboard/$guildId/commands': typeof AuthenticatedDashboardGuildIdCommandsRoute
  '/_authenticated/dashboard/$guildId/community': typeof AuthenticatedDashboardGuildIdCommunityRoute
  '/_authenticated/dashboard/$guildId/economy': typeof AuthenticatedDashboardGuildIdEconomyRoute
  '/_authenticated/dashboard/$guildId/embeds': typeof AuthenticatedDashboardGuildIdEmbedsRoute
  '/_authenticated/dashboard/$guildId/leveling': typeof AuthenticatedDashboardGuildIdLevelingRoute
  '/_authenticated/dashboard/$guildId/logs': typeof AuthenticatedDashboardGuildIdLogsRoute
  '/_authenticated/dashboard/$guildId/moderation': typeof AuthenticatedDashboardGuildIdModerationRoute
  '/_authenticated/dashboard/$guildId/permissoes': typeof AuthenticatedDashboardGuildIdPermissoesRoute
  '/_authenticated/dashboard/$guildId/premium': typeof AuthenticatedDashboardGuildIdPremiumRoute
  '/_authenticated/dashboard/$guildId/reaction-roles': typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  '/_authenticated/dashboard/$guildId/seasons': typeof AuthenticatedDashboardGuildIdSeasonsRoute
  '/_authenticated/dashboard/$guildId/social': typeof AuthenticatedDashboardGuildIdSocialRoute
  '/_authenticated/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/_authenticated/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/_authenticated/dashboard/$guildId/': typeof AuthenticatedDashboardGuildIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comandos'
    | '/login'
    | '/admin/premium'
    | '/dashboard/$guildId'
    | '/api/auth/logout'
    | '/dashboard/'
    | '/dashboard/$guildId/achievements'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/autorole'
    | '/dashboard/$guildId/badges'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/economy'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logs'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/permissoes'
    | '/dashboard/$guildId/premium'
    | '/dashboard/$guildId/reaction-roles'
    | '/dashboard/$guildId/seasons'
    | '/dashboard/$guildId/social'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/welcome'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/dashboard/$guildId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comandos'
    | '/login'
    | '/admin/premium'
    | '/api/auth/logout'
    | '/dashboard'
    | '/dashboard/$guildId/achievements'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/autorole'
    | '/dashboard/$guildId/badges'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/community'
    | '/dashboard/$guildId/economy'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logs'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/permissoes'
    | '/dashboard/$guildId/premium'
    | '/dashboard/$guildId/reaction-roles'
    | '/dashboard/$guildId/seasons'
    | '/dashboard/$guildId/social'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/welcome'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/dashboard/$guildId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/comandos'
    | '/login'
    | '/_authenticated/admin/premium'
    | '/_authenticated/dashboard/$guildId'
    | '/api/auth/logout'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/$guildId/achievements'
    | '/_authenticated/dashboard/$guildId/automod'
    | '/_authenticated/dashboard/$guildId/autorole'
    | '/_authenticated/dashboard/$guildId/badges'
    | '/_authenticated/dashboard/$guildId/commands'
    | '/_authenticated/dashboard/$guildId/community'
    | '/_authenticated/dashboard/$guildId/economy'
    | '/_authenticated/dashboard/$guildId/embeds'
    | '/_authenticated/dashboard/$guildId/leveling'
    | '/_authenticated/dashboard/$guildId/logs'
    | '/_authenticated/dashboard/$guildId/moderation'
    | '/_authenticated/dashboard/$guildId/permissoes'
    | '/_authenticated/dashboard/$guildId/premium'
    | '/_authenticated/dashboard/$guildId/reaction-roles'
    | '/_authenticated/dashboard/$guildId/seasons'
    | '/_authenticated/dashboard/$guildId/social'
    | '/_authenticated/dashboard/$guildId/tickets'
    | '/_authenticated/dashboard/$guildId/welcome'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/_authenticated/dashboard/$guildId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ComandosRoute: typeof ComandosRoute
  LoginRoute: typeof LoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordLoginRoute: typeof ApiAuthDiscordLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandos': {
      id: '/comandos'
      path: '/comandos'
      fullPath: '/comandos'
      preLoaderRoute: typeof ComandosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/$guildId': {
      id: '/_authenticated/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/premium': {
      id: '/_authenticated/admin/premium'
      path: '/admin/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AuthenticatedAdminPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$guildId/': {
      id: '/_authenticated/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/api/auth/discord/login': {
      id: '/api/auth/discord/login'
      path: '/api/auth/discord/login'
      fullPath: '/api/auth/discord/login'
      preLoaderRoute: typeof ApiAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/$guildId/welcome': {
      id: '/_authenticated/dashboard/$guildId/welcome'
      path: '/welcome'
      fullPath: '/dashboard/$guildId/welcome'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdWelcomeRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/tickets': {
      id: '/_authenticated/dashboard/$guildId/tickets'
      path: '/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdTicketsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/social': {
      id: '/_authenticated/dashboard/$guildId/social'
      path: '/social'
      fullPath: '/dashboard/$guildId/social'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdSocialRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/seasons': {
      id: '/_authenticated/dashboard/$guildId/seasons'
      path: '/seasons'
      fullPath: '/dashboard/$guildId/seasons'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdSeasonsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/reaction-roles': {
      id: '/_authenticated/dashboard/$guildId/reaction-roles'
      path: '/reaction-roles'
      fullPath: '/dashboard/$guildId/reaction-roles'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdReactionRolesRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/premium': {
      id: '/_authenticated/dashboard/$guildId/premium'
      path: '/premium'
      fullPath: '/dashboard/$guildId/premium'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdPremiumRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/permissoes': {
      id: '/_authenticated/dashboard/$guildId/permissoes'
      path: '/permissoes'
      fullPath: '/dashboard/$guildId/permissoes'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdPermissoesRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/moderation': {
      id: '/_authenticated/dashboard/$guildId/moderation'
      path: '/moderation'
      fullPath: '/dashboard/$guildId/moderation'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdModerationRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/logs': {
      id: '/_authenticated/dashboard/$guildId/logs'
      path: '/logs'
      fullPath: '/dashboard/$guildId/logs'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/leveling': {
      id: '/_authenticated/dashboard/$guildId/leveling'
      path: '/leveling'
      fullPath: '/dashboard/$guildId/leveling'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdLevelingRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/embeds': {
      id: '/_authenticated/dashboard/$guildId/embeds'
      path: '/embeds'
      fullPath: '/dashboard/$guildId/embeds'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdEmbedsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/economy': {
      id: '/_authenticated/dashboard/$guildId/economy'
      path: '/economy'
      fullPath: '/dashboard/$guildId/economy'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdEconomyRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/community': {
      id: '/_authenticated/dashboard/$guildId/community'
      path: '/community'
      fullPath: '/dashboard/$guildId/community'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdCommunityRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/commands': {
      id: '/_authenticated/dashboard/$guildId/commands'
      path: '/commands'
      fullPath: '/dashboard/$guildId/commands'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdCommandsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/badges': {
      id: '/_authenticated/dashboard/$guildId/badges'
      path: '/badges'
      fullPath: '/dashboard/$guildId/badges'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBadgesRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/autorole': {
      id: '/_authenticated/dashboard/$guildId/autorole'
      path: '/autorole'
      fullPath: '/dashboard/$guildId/autorole'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdAutoroleRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/automod': {
      id: '/_authenticated/dashboard/$guildId/automod'
      path: '/automod'
      fullPath: '/dashboard/$guildId/automod'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdAutomodRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/achievements': {
      id: '/_authenticated/dashboard/$guildId/achievements'
      path: '/achievements'
      fullPath: '/dashboard/$guildId/achievements'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdAchievementsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
  }
}

interface AuthenticatedDashboardGuildIdRouteChildren {
  AuthenticatedDashboardGuildIdAchievementsRoute: typeof AuthenticatedDashboardGuildIdAchievementsRoute
  AuthenticatedDashboardGuildIdAutomodRoute: typeof AuthenticatedDashboardGuildIdAutomodRoute
  AuthenticatedDashboardGuildIdAutoroleRoute: typeof AuthenticatedDashboardGuildIdAutoroleRoute
  AuthenticatedDashboardGuildIdBadgesRoute: typeof AuthenticatedDashboardGuildIdBadgesRoute
  AuthenticatedDashboardGuildIdCommandsRoute: typeof AuthenticatedDashboardGuildIdCommandsRoute
  AuthenticatedDashboardGuildIdCommunityRoute: typeof AuthenticatedDashboardGuildIdCommunityRoute
  AuthenticatedDashboardGuildIdEconomyRoute: typeof AuthenticatedDashboardGuildIdEconomyRoute
  AuthenticatedDashboardGuildIdEmbedsRoute: typeof AuthenticatedDashboardGuildIdEmbedsRoute
  AuthenticatedDashboardGuildIdLevelingRoute: typeof AuthenticatedDashboardGuildIdLevelingRoute
  AuthenticatedDashboardGuildIdLogsRoute: typeof AuthenticatedDashboardGuildIdLogsRoute
  AuthenticatedDashboardGuildIdModerationRoute: typeof AuthenticatedDashboardGuildIdModerationRoute
  AuthenticatedDashboardGuildIdPermissoesRoute: typeof AuthenticatedDashboardGuildIdPermissoesRoute
  AuthenticatedDashboardGuildIdPremiumRoute: typeof AuthenticatedDashboardGuildIdPremiumRoute
  AuthenticatedDashboardGuildIdReactionRolesRoute: typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  AuthenticatedDashboardGuildIdSeasonsRoute: typeof AuthenticatedDashboardGuildIdSeasonsRoute
  AuthenticatedDashboardGuildIdSocialRoute: typeof AuthenticatedDashboardGuildIdSocialRoute
  AuthenticatedDashboardGuildIdTicketsRoute: typeof AuthenticatedDashboardGuildIdTicketsRoute
  AuthenticatedDashboardGuildIdWelcomeRoute: typeof AuthenticatedDashboardGuildIdWelcomeRoute
  AuthenticatedDashboardGuildIdIndexRoute: typeof AuthenticatedDashboardGuildIdIndexRoute
}

const AuthenticatedDashboardGuildIdRouteChildren: AuthenticatedDashboardGuildIdRouteChildren =
  {
    AuthenticatedDashboardGuildIdAchievementsRoute:
      AuthenticatedDashboardGuildIdAchievementsRoute,
    AuthenticatedDashboardGuildIdAutomodRoute:
      AuthenticatedDashboardGuildIdAutomodRoute,
    AuthenticatedDashboardGuildIdAutoroleRoute:
      AuthenticatedDashboardGuildIdAutoroleRoute,
    AuthenticatedDashboardGuildIdBadgesRoute:
      AuthenticatedDashboardGuildIdBadgesRoute,
    AuthenticatedDashboardGuildIdCommandsRoute:
      AuthenticatedDashboardGuildIdCommandsRoute,
    AuthenticatedDashboardGuildIdCommunityRoute:
      AuthenticatedDashboardGuildIdCommunityRoute,
    AuthenticatedDashboardGuildIdEconomyRoute:
      AuthenticatedDashboardGuildIdEconomyRoute,
    AuthenticatedDashboardGuildIdEmbedsRoute:
      AuthenticatedDashboardGuildIdEmbedsRoute,
    AuthenticatedDashboardGuildIdLevelingRoute:
      AuthenticatedDashboardGuildIdLevelingRoute,
    AuthenticatedDashboardGuildIdLogsRoute:
      AuthenticatedDashboardGuildIdLogsRoute,
    AuthenticatedDashboardGuildIdModerationRoute:
      AuthenticatedDashboardGuildIdModerationRoute,
    AuthenticatedDashboardGuildIdPermissoesRoute:
      AuthenticatedDashboardGuildIdPermissoesRoute,
    AuthenticatedDashboardGuildIdPremiumRoute:
      AuthenticatedDashboardGuildIdPremiumRoute,
    AuthenticatedDashboardGuildIdReactionRolesRoute:
      AuthenticatedDashboardGuildIdReactionRolesRoute,
    AuthenticatedDashboardGuildIdSeasonsRoute:
      AuthenticatedDashboardGuildIdSeasonsRoute,
    AuthenticatedDashboardGuildIdSocialRoute:
      AuthenticatedDashboardGuildIdSocialRoute,
    AuthenticatedDashboardGuildIdTicketsRoute:
      AuthenticatedDashboardGuildIdTicketsRoute,
    AuthenticatedDashboardGuildIdWelcomeRoute:
      AuthenticatedDashboardGuildIdWelcomeRoute,
    AuthenticatedDashboardGuildIdIndexRoute:
      AuthenticatedDashboardGuildIdIndexRoute,
  }

const AuthenticatedDashboardGuildIdRouteWithChildren =
  AuthenticatedDashboardGuildIdRoute._addFileChildren(
    AuthenticatedDashboardGuildIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminPremiumRoute: typeof AuthenticatedAdminPremiumRoute
  AuthenticatedDashboardGuildIdRoute: typeof AuthenticatedDashboardGuildIdRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminPremiumRoute: AuthenticatedAdminPremiumRoute,
  AuthenticatedDashboardGuildIdRoute:
    AuthenticatedDashboardGuildIdRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ComandosRoute: ComandosRoute,
  LoginRoute: LoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordLoginRoute: ApiAuthDiscordLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
