/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as StatusRouteImport } from './routes/status'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ComandosRouteImport } from './routes/comandos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServidoresRouteImport } from './routes/_authenticated/servidores'
import { Route as AuthenticatedDevLogsRouteImport } from './routes/_authenticated/dev-logs'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiPublicBotGuildPresenceRouteImport } from './routes/api/public/bot-guild-presence'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as AuthenticatedGGuildIdRouteImport } from './routes/_authenticated/g.$guildId'
import { Route as AuthenticatedDashboardSlugRouteImport } from './routes/_authenticated/dashboard.$slug'
import { Route as AuthenticatedAdminPremiumRouteImport } from './routes/_authenticated/admin.premium'
import { Route as AuthenticatedDashboardSlugIndexRouteImport } from './routes/_authenticated/dashboard.$slug.index'
import { Route as ApiPublicCronWeeklyRankingRouteImport } from './routes/api/public/cron/weekly-ranking'
import { Route as ApiPublicCronCosmeticRotationRouteImport } from './routes/api/public/cron/cosmetic-rotation'
import { Route as ApiAuthDiscordLoginRouteImport } from './routes/api/auth/discord/login'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'
import { Route as AuthenticatedGGuildIdSplatRouteImport } from './routes/_authenticated/g.$guildId.$'
import { Route as AuthenticatedDashboardSlugTicketsRouteImport } from './routes/_authenticated/dashboard.$slug.tickets'
import { Route as AuthenticatedDashboardSlugTemporadasRouteImport } from './routes/_authenticated/dashboard.$slug.temporadas'
import { Route as AuthenticatedDashboardSlugSocialRouteImport } from './routes/_authenticated/dashboard.$slug.social'
import { Route as AuthenticatedDashboardSlugPremiumRouteImport } from './routes/_authenticated/dashboard.$slug.premium'
import { Route as AuthenticatedDashboardSlugPermissoesRouteImport } from './routes/_authenticated/dashboard.$slug.permissoes'
import { Route as AuthenticatedDashboardSlugNiveisRouteImport } from './routes/_authenticated/dashboard.$slug.niveis'
import { Route as AuthenticatedDashboardSlugModeracaoRouteImport } from './routes/_authenticated/dashboard.$slug.moderacao'
import { Route as AuthenticatedDashboardSlugLogsRouteImport } from './routes/_authenticated/dashboard.$slug.logs'
import { Route as AuthenticatedDashboardSlugEmbedsRouteImport } from './routes/_authenticated/dashboard.$slug.embeds'
import { Route as AuthenticatedDashboardSlugEconomiaRouteImport } from './routes/_authenticated/dashboard.$slug.economia'
import { Route as AuthenticatedDashboardSlugConquistasRouteImport } from './routes/_authenticated/dashboard.$slug.conquistas'
import { Route as AuthenticatedDashboardSlugComunidadeRouteImport } from './routes/_authenticated/dashboard.$slug.comunidade'
import { Route as AuthenticatedDashboardSlugComandosBotRouteImport } from './routes/_authenticated/dashboard.$slug.comandos-bot'
import { Route as AuthenticatedDashboardSlugCargosReacaoRouteImport } from './routes/_authenticated/dashboard.$slug.cargos-reacao'
import { Route as AuthenticatedDashboardSlugCargoAutomaticoRouteImport } from './routes/_authenticated/dashboard.$slug.cargo-automatico'
import { Route as AuthenticatedDashboardSlugBoasVindasRouteImport } from './routes/_authenticated/dashboard.$slug.boas-vindas'
import { Route as AuthenticatedDashboardSlugBadgesRouteImport } from './routes/_authenticated/dashboard.$slug.badges'
import { Route as AuthenticatedDashboardSlugAssetsRouteImport } from './routes/_authenticated/dashboard.$slug.assets'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandosRoute = ComandosRouteImport.update({
  id: '/comandos',
  path: '/comandos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServidoresRoute = AuthenticatedServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevLogsRoute = AuthenticatedDevLogsRouteImport.update({
  id: '/dev-logs',
  path: '/dev-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicBotGuildPresenceRoute =
  ApiPublicBotGuildPresenceRouteImport.update({
    id: '/api/public/bot-guild-presence',
    path: '/api/public/bot-guild-presence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGGuildIdRoute = AuthenticatedGGuildIdRouteImport.update({
  id: '/g/$guildId',
  path: '/g/$guildId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardSlugRoute =
  AuthenticatedDashboardSlugRouteImport.update({
    id: '/dashboard/$slug',
    path: '/dashboard/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPremiumRoute =
  AuthenticatedAdminPremiumRouteImport.update({
    id: '/admin/premium',
    path: '/admin/premium',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardSlugIndexRoute =
  AuthenticatedDashboardSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const ApiPublicCronWeeklyRankingRoute =
  ApiPublicCronWeeklyRankingRouteImport.update({
    id: '/api/public/cron/weekly-ranking',
    path: '/api/public/cron/weekly-ranking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCosmeticRotationRoute =
  ApiPublicCronCosmeticRotationRouteImport.update({
    id: '/api/public/cron/cosmetic-rotation',
    path: '/api/public/cron/cosmetic-rotation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscordLoginRoute = ApiAuthDiscordLoginRouteImport.update({
  id: '/api/auth/discord/login',
  path: '/api/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGGuildIdSplatRoute =
  AuthenticatedGGuildIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedGGuildIdRoute,
  } as any)
const AuthenticatedDashboardSlugTicketsRoute =
  AuthenticatedDashboardSlugTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugTemporadasRoute =
  AuthenticatedDashboardSlugTemporadasRouteImport.update({
    id: '/temporadas',
    path: '/temporadas',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugSocialRoute =
  AuthenticatedDashboardSlugSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugPremiumRoute =
  AuthenticatedDashboardSlugPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugPermissoesRoute =
  AuthenticatedDashboardSlugPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugNiveisRoute =
  AuthenticatedDashboardSlugNiveisRouteImport.update({
    id: '/niveis',
    path: '/niveis',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugModeracaoRoute =
  AuthenticatedDashboardSlugModeracaoRouteImport.update({
    id: '/moderacao',
    path: '/moderacao',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugLogsRoute =
  AuthenticatedDashboardSlugLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugEmbedsRoute =
  AuthenticatedDashboardSlugEmbedsRouteImport.update({
    id: '/embeds',
    path: '/embeds',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugEconomiaRoute =
  AuthenticatedDashboardSlugEconomiaRouteImport.update({
    id: '/economia',
    path: '/economia',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugConquistasRoute =
  AuthenticatedDashboardSlugConquistasRouteImport.update({
    id: '/conquistas',
    path: '/conquistas',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugComunidadeRoute =
  AuthenticatedDashboardSlugComunidadeRouteImport.update({
    id: '/comunidade',
    path: '/comunidade',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugComandosBotRoute =
  AuthenticatedDashboardSlugComandosBotRouteImport.update({
    id: '/comandos-bot',
    path: '/comandos-bot',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugCargosReacaoRoute =
  AuthenticatedDashboardSlugCargosReacaoRouteImport.update({
    id: '/cargos-reacao',
    path: '/cargos-reacao',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugCargoAutomaticoRoute =
  AuthenticatedDashboardSlugCargoAutomaticoRouteImport.update({
    id: '/cargo-automatico',
    path: '/cargo-automatico',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugBoasVindasRoute =
  AuthenticatedDashboardSlugBoasVindasRouteImport.update({
    id: '/boas-vindas',
    path: '/boas-vindas',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugBadgesRoute =
  AuthenticatedDashboardSlugBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)
const AuthenticatedDashboardSlugAssetsRoute =
  AuthenticatedDashboardSlugAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedDashboardSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/comandos': typeof ComandosRoute
  '/daily': typeof DailyRoute
  '/docs': typeof DocsRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/premium': typeof PremiumRoute
  '/recursos': typeof RecursosRoute
  '/status': typeof StatusRoute
  '/suporte': typeof SuporteRoute
  '/dev-logs': typeof AuthenticatedDevLogsRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/dashboard/$slug': typeof AuthenticatedDashboardSlugRouteWithChildren
  '/g/$guildId': typeof AuthenticatedGGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/public/bot-guild-presence': typeof ApiPublicBotGuildPresenceRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$slug/assets': typeof AuthenticatedDashboardSlugAssetsRoute
  '/dashboard/$slug/badges': typeof AuthenticatedDashboardSlugBadgesRoute
  '/dashboard/$slug/boas-vindas': typeof AuthenticatedDashboardSlugBoasVindasRoute
  '/dashboard/$slug/cargo-automatico': typeof AuthenticatedDashboardSlugCargoAutomaticoRoute
  '/dashboard/$slug/cargos-reacao': typeof AuthenticatedDashboardSlugCargosReacaoRoute
  '/dashboard/$slug/comandos-bot': typeof AuthenticatedDashboardSlugComandosBotRoute
  '/dashboard/$slug/comunidade': typeof AuthenticatedDashboardSlugComunidadeRoute
  '/dashboard/$slug/conquistas': typeof AuthenticatedDashboardSlugConquistasRoute
  '/dashboard/$slug/economia': typeof AuthenticatedDashboardSlugEconomiaRoute
  '/dashboard/$slug/embeds': typeof AuthenticatedDashboardSlugEmbedsRoute
  '/dashboard/$slug/logs': typeof AuthenticatedDashboardSlugLogsRoute
  '/dashboard/$slug/moderacao': typeof AuthenticatedDashboardSlugModeracaoRoute
  '/dashboard/$slug/niveis': typeof AuthenticatedDashboardSlugNiveisRoute
  '/dashboard/$slug/permissoes': typeof AuthenticatedDashboardSlugPermissoesRoute
  '/dashboard/$slug/premium': typeof AuthenticatedDashboardSlugPremiumRoute
  '/dashboard/$slug/social': typeof AuthenticatedDashboardSlugSocialRoute
  '/dashboard/$slug/temporadas': typeof AuthenticatedDashboardSlugTemporadasRoute
  '/dashboard/$slug/tickets': typeof AuthenticatedDashboardSlugTicketsRoute
  '/g/$guildId/$': typeof AuthenticatedGGuildIdSplatRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/public/cron/cosmetic-rotation': typeof ApiPublicCronCosmeticRotationRoute
  '/api/public/cron/weekly-ranking': typeof ApiPublicCronWeeklyRankingRoute
  '/dashboard/$slug/': typeof AuthenticatedDashboardSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/comandos': typeof ComandosRoute
  '/daily': typeof DailyRoute
  '/docs': typeof DocsRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/premium': typeof PremiumRoute
  '/recursos': typeof RecursosRoute
  '/status': typeof StatusRoute
  '/suporte': typeof SuporteRoute
  '/dev-logs': typeof AuthenticatedDevLogsRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/g/$guildId': typeof AuthenticatedGGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/public/bot-guild-presence': typeof ApiPublicBotGuildPresenceRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$slug/assets': typeof AuthenticatedDashboardSlugAssetsRoute
  '/dashboard/$slug/badges': typeof AuthenticatedDashboardSlugBadgesRoute
  '/dashboard/$slug/boas-vindas': typeof AuthenticatedDashboardSlugBoasVindasRoute
  '/dashboard/$slug/cargo-automatico': typeof AuthenticatedDashboardSlugCargoAutomaticoRoute
  '/dashboard/$slug/cargos-reacao': typeof AuthenticatedDashboardSlugCargosReacaoRoute
  '/dashboard/$slug/comandos-bot': typeof AuthenticatedDashboardSlugComandosBotRoute
  '/dashboard/$slug/comunidade': typeof AuthenticatedDashboardSlugComunidadeRoute
  '/dashboard/$slug/conquistas': typeof AuthenticatedDashboardSlugConquistasRoute
  '/dashboard/$slug/economia': typeof AuthenticatedDashboardSlugEconomiaRoute
  '/dashboard/$slug/embeds': typeof AuthenticatedDashboardSlugEmbedsRoute
  '/dashboard/$slug/logs': typeof AuthenticatedDashboardSlugLogsRoute
  '/dashboard/$slug/moderacao': typeof AuthenticatedDashboardSlugModeracaoRoute
  '/dashboard/$slug/niveis': typeof AuthenticatedDashboardSlugNiveisRoute
  '/dashboard/$slug/permissoes': typeof AuthenticatedDashboardSlugPermissoesRoute
  '/dashboard/$slug/premium': typeof AuthenticatedDashboardSlugPremiumRoute
  '/dashboard/$slug/social': typeof AuthenticatedDashboardSlugSocialRoute
  '/dashboard/$slug/temporadas': typeof AuthenticatedDashboardSlugTemporadasRoute
  '/dashboard/$slug/tickets': typeof AuthenticatedDashboardSlugTicketsRoute
  '/g/$guildId/$': typeof AuthenticatedGGuildIdSplatRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/public/cron/cosmetic-rotation': typeof ApiPublicCronCosmeticRotationRoute
  '/api/public/cron/weekly-ranking': typeof ApiPublicCronWeeklyRankingRoute
  '/dashboard/$slug': typeof AuthenticatedDashboardSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/comandos': typeof ComandosRoute
  '/daily': typeof DailyRoute
  '/docs': typeof DocsRoute
  '/entrar': typeof EntrarRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/premium': typeof PremiumRoute
  '/recursos': typeof RecursosRoute
  '/status': typeof StatusRoute
  '/suporte': typeof SuporteRoute
  '/_authenticated/dev-logs': typeof AuthenticatedDevLogsRoute
  '/_authenticated/servidores': typeof AuthenticatedServidoresRoute
  '/_authenticated/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/_authenticated/dashboard/$slug': typeof AuthenticatedDashboardSlugRouteWithChildren
  '/_authenticated/g/$guildId': typeof AuthenticatedGGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/public/bot-guild-presence': typeof ApiPublicBotGuildPresenceRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/$slug/assets': typeof AuthenticatedDashboardSlugAssetsRoute
  '/_authenticated/dashboard/$slug/badges': typeof AuthenticatedDashboardSlugBadgesRoute
  '/_authenticated/dashboard/$slug/boas-vindas': typeof AuthenticatedDashboardSlugBoasVindasRoute
  '/_authenticated/dashboard/$slug/cargo-automatico': typeof AuthenticatedDashboardSlugCargoAutomaticoRoute
  '/_authenticated/dashboard/$slug/cargos-reacao': typeof AuthenticatedDashboardSlugCargosReacaoRoute
  '/_authenticated/dashboard/$slug/comandos-bot': typeof AuthenticatedDashboardSlugComandosBotRoute
  '/_authenticated/dashboard/$slug/comunidade': typeof AuthenticatedDashboardSlugComunidadeRoute
  '/_authenticated/dashboard/$slug/conquistas': typeof AuthenticatedDashboardSlugConquistasRoute
  '/_authenticated/dashboard/$slug/economia': typeof AuthenticatedDashboardSlugEconomiaRoute
  '/_authenticated/dashboard/$slug/embeds': typeof AuthenticatedDashboardSlugEmbedsRoute
  '/_authenticated/dashboard/$slug/logs': typeof AuthenticatedDashboardSlugLogsRoute
  '/_authenticated/dashboard/$slug/moderacao': typeof AuthenticatedDashboardSlugModeracaoRoute
  '/_authenticated/dashboard/$slug/niveis': typeof AuthenticatedDashboardSlugNiveisRoute
  '/_authenticated/dashboard/$slug/permissoes': typeof AuthenticatedDashboardSlugPermissoesRoute
  '/_authenticated/dashboard/$slug/premium': typeof AuthenticatedDashboardSlugPremiumRoute
  '/_authenticated/dashboard/$slug/social': typeof AuthenticatedDashboardSlugSocialRoute
  '/_authenticated/dashboard/$slug/temporadas': typeof AuthenticatedDashboardSlugTemporadasRoute
  '/_authenticated/dashboard/$slug/tickets': typeof AuthenticatedDashboardSlugTicketsRoute
  '/_authenticated/g/$guildId/$': typeof AuthenticatedGGuildIdSplatRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
  '/api/public/cron/cosmetic-rotation': typeof ApiPublicCronCosmeticRotationRoute
  '/api/public/cron/weekly-ranking': typeof ApiPublicCronWeeklyRankingRoute
  '/_authenticated/dashboard/$slug/': typeof AuthenticatedDashboardSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/comandos'
    | '/daily'
    | '/docs'
    | '/entrar'
    | '/login'
    | '/loja'
    | '/premium'
    | '/recursos'
    | '/status'
    | '/suporte'
    | '/dev-logs'
    | '/servidores'
    | '/admin/premium'
    | '/dashboard/$slug'
    | '/g/$guildId'
    | '/api/auth/logout'
    | '/api/public/bot-guild-presence'
    | '/dashboard/'
    | '/dashboard/$slug/assets'
    | '/dashboard/$slug/badges'
    | '/dashboard/$slug/boas-vindas'
    | '/dashboard/$slug/cargo-automatico'
    | '/dashboard/$slug/cargos-reacao'
    | '/dashboard/$slug/comandos-bot'
    | '/dashboard/$slug/comunidade'
    | '/dashboard/$slug/conquistas'
    | '/dashboard/$slug/economia'
    | '/dashboard/$slug/embeds'
    | '/dashboard/$slug/logs'
    | '/dashboard/$slug/moderacao'
    | '/dashboard/$slug/niveis'
    | '/dashboard/$slug/permissoes'
    | '/dashboard/$slug/premium'
    | '/dashboard/$slug/social'
    | '/dashboard/$slug/temporadas'
    | '/dashboard/$slug/tickets'
    | '/g/$guildId/$'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/api/public/cron/cosmetic-rotation'
    | '/api/public/cron/weekly-ranking'
    | '/dashboard/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/comandos'
    | '/daily'
    | '/docs'
    | '/entrar'
    | '/login'
    | '/loja'
    | '/premium'
    | '/recursos'
    | '/status'
    | '/suporte'
    | '/dev-logs'
    | '/servidores'
    | '/admin/premium'
    | '/g/$guildId'
    | '/api/auth/logout'
    | '/api/public/bot-guild-presence'
    | '/dashboard'
    | '/dashboard/$slug/assets'
    | '/dashboard/$slug/badges'
    | '/dashboard/$slug/boas-vindas'
    | '/dashboard/$slug/cargo-automatico'
    | '/dashboard/$slug/cargos-reacao'
    | '/dashboard/$slug/comandos-bot'
    | '/dashboard/$slug/comunidade'
    | '/dashboard/$slug/conquistas'
    | '/dashboard/$slug/economia'
    | '/dashboard/$slug/embeds'
    | '/dashboard/$slug/logs'
    | '/dashboard/$slug/moderacao'
    | '/dashboard/$slug/niveis'
    | '/dashboard/$slug/permissoes'
    | '/dashboard/$slug/premium'
    | '/dashboard/$slug/social'
    | '/dashboard/$slug/temporadas'
    | '/dashboard/$slug/tickets'
    | '/g/$guildId/$'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/api/public/cron/cosmetic-rotation'
    | '/api/public/cron/weekly-ranking'
    | '/dashboard/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/comandos'
    | '/daily'
    | '/docs'
    | '/entrar'
    | '/login'
    | '/loja'
    | '/premium'
    | '/recursos'
    | '/status'
    | '/suporte'
    | '/_authenticated/dev-logs'
    | '/_authenticated/servidores'
    | '/_authenticated/admin/premium'
    | '/_authenticated/dashboard/$slug'
    | '/_authenticated/g/$guildId'
    | '/api/auth/logout'
    | '/api/public/bot-guild-presence'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/$slug/assets'
    | '/_authenticated/dashboard/$slug/badges'
    | '/_authenticated/dashboard/$slug/boas-vindas'
    | '/_authenticated/dashboard/$slug/cargo-automatico'
    | '/_authenticated/dashboard/$slug/cargos-reacao'
    | '/_authenticated/dashboard/$slug/comandos-bot'
    | '/_authenticated/dashboard/$slug/comunidade'
    | '/_authenticated/dashboard/$slug/conquistas'
    | '/_authenticated/dashboard/$slug/economia'
    | '/_authenticated/dashboard/$slug/embeds'
    | '/_authenticated/dashboard/$slug/logs'
    | '/_authenticated/dashboard/$slug/moderacao'
    | '/_authenticated/dashboard/$slug/niveis'
    | '/_authenticated/dashboard/$slug/permissoes'
    | '/_authenticated/dashboard/$slug/premium'
    | '/_authenticated/dashboard/$slug/social'
    | '/_authenticated/dashboard/$slug/temporadas'
    | '/_authenticated/dashboard/$slug/tickets'
    | '/_authenticated/g/$guildId/$'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
    | '/api/public/cron/cosmetic-rotation'
    | '/api/public/cron/weekly-ranking'
    | '/_authenticated/dashboard/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  ComandosRoute: typeof ComandosRoute
  DailyRoute: typeof DailyRoute
  DocsRoute: typeof DocsRoute
  EntrarRoute: typeof EntrarRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  PremiumRoute: typeof PremiumRoute
  RecursosRoute: typeof RecursosRoute
  StatusRoute: typeof StatusRoute
  SuporteRoute: typeof SuporteRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiPublicBotGuildPresenceRoute: typeof ApiPublicBotGuildPresenceRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordLoginRoute: typeof ApiAuthDiscordLoginRoute
  ApiPublicCronCosmeticRotationRoute: typeof ApiPublicCronCosmeticRotationRoute
  ApiPublicCronWeeklyRankingRoute: typeof ApiPublicCronWeeklyRankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandos': {
      id: '/comandos'
      path: '/comandos'
      fullPath: '/comandos'
      preLoaderRoute: typeof ComandosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servidores': {
      id: '/_authenticated/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof AuthenticatedServidoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev-logs': {
      id: '/_authenticated/dev-logs'
      path: '/dev-logs'
      fullPath: '/dev-logs'
      preLoaderRoute: typeof AuthenticatedDevLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/bot-guild-presence': {
      id: '/api/public/bot-guild-presence'
      path: '/api/public/bot-guild-presence'
      fullPath: '/api/public/bot-guild-presence'
      preLoaderRoute: typeof ApiPublicBotGuildPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/g/$guildId': {
      id: '/_authenticated/g/$guildId'
      path: '/g/$guildId'
      fullPath: '/g/$guildId'
      preLoaderRoute: typeof AuthenticatedGGuildIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$slug': {
      id: '/_authenticated/dashboard/$slug'
      path: '/dashboard/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/premium': {
      id: '/_authenticated/admin/premium'
      path: '/admin/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AuthenticatedAdminPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$slug/': {
      id: '/_authenticated/dashboard/$slug/'
      path: '/'
      fullPath: '/dashboard/$slug/'
      preLoaderRoute: typeof AuthenticatedDashboardSlugIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/api/public/cron/weekly-ranking': {
      id: '/api/public/cron/weekly-ranking'
      path: '/api/public/cron/weekly-ranking'
      fullPath: '/api/public/cron/weekly-ranking'
      preLoaderRoute: typeof ApiPublicCronWeeklyRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cosmetic-rotation': {
      id: '/api/public/cron/cosmetic-rotation'
      path: '/api/public/cron/cosmetic-rotation'
      fullPath: '/api/public/cron/cosmetic-rotation'
      preLoaderRoute: typeof ApiPublicCronCosmeticRotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/login': {
      id: '/api/auth/discord/login'
      path: '/api/auth/discord/login'
      fullPath: '/api/auth/discord/login'
      preLoaderRoute: typeof ApiAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/g/$guildId/$': {
      id: '/_authenticated/g/$guildId/$'
      path: '/$'
      fullPath: '/g/$guildId/$'
      preLoaderRoute: typeof AuthenticatedGGuildIdSplatRouteImport
      parentRoute: typeof AuthenticatedGGuildIdRoute
    }
    '/_authenticated/dashboard/$slug/tickets': {
      id: '/_authenticated/dashboard/$slug/tickets'
      path: '/tickets'
      fullPath: '/dashboard/$slug/tickets'
      preLoaderRoute: typeof AuthenticatedDashboardSlugTicketsRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/temporadas': {
      id: '/_authenticated/dashboard/$slug/temporadas'
      path: '/temporadas'
      fullPath: '/dashboard/$slug/temporadas'
      preLoaderRoute: typeof AuthenticatedDashboardSlugTemporadasRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/social': {
      id: '/_authenticated/dashboard/$slug/social'
      path: '/social'
      fullPath: '/dashboard/$slug/social'
      preLoaderRoute: typeof AuthenticatedDashboardSlugSocialRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/premium': {
      id: '/_authenticated/dashboard/$slug/premium'
      path: '/premium'
      fullPath: '/dashboard/$slug/premium'
      preLoaderRoute: typeof AuthenticatedDashboardSlugPremiumRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/permissoes': {
      id: '/_authenticated/dashboard/$slug/permissoes'
      path: '/permissoes'
      fullPath: '/dashboard/$slug/permissoes'
      preLoaderRoute: typeof AuthenticatedDashboardSlugPermissoesRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/niveis': {
      id: '/_authenticated/dashboard/$slug/niveis'
      path: '/niveis'
      fullPath: '/dashboard/$slug/niveis'
      preLoaderRoute: typeof AuthenticatedDashboardSlugNiveisRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/moderacao': {
      id: '/_authenticated/dashboard/$slug/moderacao'
      path: '/moderacao'
      fullPath: '/dashboard/$slug/moderacao'
      preLoaderRoute: typeof AuthenticatedDashboardSlugModeracaoRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/logs': {
      id: '/_authenticated/dashboard/$slug/logs'
      path: '/logs'
      fullPath: '/dashboard/$slug/logs'
      preLoaderRoute: typeof AuthenticatedDashboardSlugLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/embeds': {
      id: '/_authenticated/dashboard/$slug/embeds'
      path: '/embeds'
      fullPath: '/dashboard/$slug/embeds'
      preLoaderRoute: typeof AuthenticatedDashboardSlugEmbedsRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/economia': {
      id: '/_authenticated/dashboard/$slug/economia'
      path: '/economia'
      fullPath: '/dashboard/$slug/economia'
      preLoaderRoute: typeof AuthenticatedDashboardSlugEconomiaRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/conquistas': {
      id: '/_authenticated/dashboard/$slug/conquistas'
      path: '/conquistas'
      fullPath: '/dashboard/$slug/conquistas'
      preLoaderRoute: typeof AuthenticatedDashboardSlugConquistasRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/comunidade': {
      id: '/_authenticated/dashboard/$slug/comunidade'
      path: '/comunidade'
      fullPath: '/dashboard/$slug/comunidade'
      preLoaderRoute: typeof AuthenticatedDashboardSlugComunidadeRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/comandos-bot': {
      id: '/_authenticated/dashboard/$slug/comandos-bot'
      path: '/comandos-bot'
      fullPath: '/dashboard/$slug/comandos-bot'
      preLoaderRoute: typeof AuthenticatedDashboardSlugComandosBotRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/cargos-reacao': {
      id: '/_authenticated/dashboard/$slug/cargos-reacao'
      path: '/cargos-reacao'
      fullPath: '/dashboard/$slug/cargos-reacao'
      preLoaderRoute: typeof AuthenticatedDashboardSlugCargosReacaoRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/cargo-automatico': {
      id: '/_authenticated/dashboard/$slug/cargo-automatico'
      path: '/cargo-automatico'
      fullPath: '/dashboard/$slug/cargo-automatico'
      preLoaderRoute: typeof AuthenticatedDashboardSlugCargoAutomaticoRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/boas-vindas': {
      id: '/_authenticated/dashboard/$slug/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/dashboard/$slug/boas-vindas'
      preLoaderRoute: typeof AuthenticatedDashboardSlugBoasVindasRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/badges': {
      id: '/_authenticated/dashboard/$slug/badges'
      path: '/badges'
      fullPath: '/dashboard/$slug/badges'
      preLoaderRoute: typeof AuthenticatedDashboardSlugBadgesRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
    '/_authenticated/dashboard/$slug/assets': {
      id: '/_authenticated/dashboard/$slug/assets'
      path: '/assets'
      fullPath: '/dashboard/$slug/assets'
      preLoaderRoute: typeof AuthenticatedDashboardSlugAssetsRouteImport
      parentRoute: typeof AuthenticatedDashboardSlugRoute
    }
  }
}

interface AuthenticatedDashboardSlugRouteChildren {
  AuthenticatedDashboardSlugAssetsRoute: typeof AuthenticatedDashboardSlugAssetsRoute
  AuthenticatedDashboardSlugBadgesRoute: typeof AuthenticatedDashboardSlugBadgesRoute
  AuthenticatedDashboardSlugBoasVindasRoute: typeof AuthenticatedDashboardSlugBoasVindasRoute
  AuthenticatedDashboardSlugCargoAutomaticoRoute: typeof AuthenticatedDashboardSlugCargoAutomaticoRoute
  AuthenticatedDashboardSlugCargosReacaoRoute: typeof AuthenticatedDashboardSlugCargosReacaoRoute
  AuthenticatedDashboardSlugComandosBotRoute: typeof AuthenticatedDashboardSlugComandosBotRoute
  AuthenticatedDashboardSlugComunidadeRoute: typeof AuthenticatedDashboardSlugComunidadeRoute
  AuthenticatedDashboardSlugConquistasRoute: typeof AuthenticatedDashboardSlugConquistasRoute
  AuthenticatedDashboardSlugEconomiaRoute: typeof AuthenticatedDashboardSlugEconomiaRoute
  AuthenticatedDashboardSlugEmbedsRoute: typeof AuthenticatedDashboardSlugEmbedsRoute
  AuthenticatedDashboardSlugLogsRoute: typeof AuthenticatedDashboardSlugLogsRoute
  AuthenticatedDashboardSlugModeracaoRoute: typeof AuthenticatedDashboardSlugModeracaoRoute
  AuthenticatedDashboardSlugNiveisRoute: typeof AuthenticatedDashboardSlugNiveisRoute
  AuthenticatedDashboardSlugPermissoesRoute: typeof AuthenticatedDashboardSlugPermissoesRoute
  AuthenticatedDashboardSlugPremiumRoute: typeof AuthenticatedDashboardSlugPremiumRoute
  AuthenticatedDashboardSlugSocialRoute: typeof AuthenticatedDashboardSlugSocialRoute
  AuthenticatedDashboardSlugTemporadasRoute: typeof AuthenticatedDashboardSlugTemporadasRoute
  AuthenticatedDashboardSlugTicketsRoute: typeof AuthenticatedDashboardSlugTicketsRoute
  AuthenticatedDashboardSlugIndexRoute: typeof AuthenticatedDashboardSlugIndexRoute
}

const AuthenticatedDashboardSlugRouteChildren: AuthenticatedDashboardSlugRouteChildren =
  {
    AuthenticatedDashboardSlugAssetsRoute:
      AuthenticatedDashboardSlugAssetsRoute,
    AuthenticatedDashboardSlugBadgesRoute:
      AuthenticatedDashboardSlugBadgesRoute,
    AuthenticatedDashboardSlugBoasVindasRoute:
      AuthenticatedDashboardSlugBoasVindasRoute,
    AuthenticatedDashboardSlugCargoAutomaticoRoute:
      AuthenticatedDashboardSlugCargoAutomaticoRoute,
    AuthenticatedDashboardSlugCargosReacaoRoute:
      AuthenticatedDashboardSlugCargosReacaoRoute,
    AuthenticatedDashboardSlugComandosBotRoute:
      AuthenticatedDashboardSlugComandosBotRoute,
    AuthenticatedDashboardSlugComunidadeRoute:
      AuthenticatedDashboardSlugComunidadeRoute,
    AuthenticatedDashboardSlugConquistasRoute:
      AuthenticatedDashboardSlugConquistasRoute,
    AuthenticatedDashboardSlugEconomiaRoute:
      AuthenticatedDashboardSlugEconomiaRoute,
    AuthenticatedDashboardSlugEmbedsRoute:
      AuthenticatedDashboardSlugEmbedsRoute,
    AuthenticatedDashboardSlugLogsRoute: AuthenticatedDashboardSlugLogsRoute,
    AuthenticatedDashboardSlugModeracaoRoute:
      AuthenticatedDashboardSlugModeracaoRoute,
    AuthenticatedDashboardSlugNiveisRoute:
      AuthenticatedDashboardSlugNiveisRoute,
    AuthenticatedDashboardSlugPermissoesRoute:
      AuthenticatedDashboardSlugPermissoesRoute,
    AuthenticatedDashboardSlugPremiumRoute:
      AuthenticatedDashboardSlugPremiumRoute,
    AuthenticatedDashboardSlugSocialRoute:
      AuthenticatedDashboardSlugSocialRoute,
    AuthenticatedDashboardSlugTemporadasRoute:
      AuthenticatedDashboardSlugTemporadasRoute,
    AuthenticatedDashboardSlugTicketsRoute:
      AuthenticatedDashboardSlugTicketsRoute,
    AuthenticatedDashboardSlugIndexRoute: AuthenticatedDashboardSlugIndexRoute,
  }

const AuthenticatedDashboardSlugRouteWithChildren =
  AuthenticatedDashboardSlugRoute._addFileChildren(
    AuthenticatedDashboardSlugRouteChildren,
  )

interface AuthenticatedGGuildIdRouteChildren {
  AuthenticatedGGuildIdSplatRoute: typeof AuthenticatedGGuildIdSplatRoute
}

const AuthenticatedGGuildIdRouteChildren: AuthenticatedGGuildIdRouteChildren = {
  AuthenticatedGGuildIdSplatRoute: AuthenticatedGGuildIdSplatRoute,
}

const AuthenticatedGGuildIdRouteWithChildren =
  AuthenticatedGGuildIdRoute._addFileChildren(
    AuthenticatedGGuildIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDevLogsRoute: typeof AuthenticatedDevLogsRoute
  AuthenticatedServidoresRoute: typeof AuthenticatedServidoresRoute
  AuthenticatedAdminPremiumRoute: typeof AuthenticatedAdminPremiumRoute
  AuthenticatedDashboardSlugRoute: typeof AuthenticatedDashboardSlugRouteWithChildren
  AuthenticatedGGuildIdRoute: typeof AuthenticatedGGuildIdRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDevLogsRoute: AuthenticatedDevLogsRoute,
  AuthenticatedServidoresRoute: AuthenticatedServidoresRoute,
  AuthenticatedAdminPremiumRoute: AuthenticatedAdminPremiumRoute,
  AuthenticatedDashboardSlugRoute: AuthenticatedDashboardSlugRouteWithChildren,
  AuthenticatedGGuildIdRoute: AuthenticatedGGuildIdRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  ComandosRoute: ComandosRoute,
  DailyRoute: DailyRoute,
  DocsRoute: DocsRoute,
  EntrarRoute: EntrarRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  PremiumRoute: PremiumRoute,
  RecursosRoute: RecursosRoute,
  StatusRoute: StatusRoute,
  SuporteRoute: SuporteRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiPublicBotGuildPresenceRoute: ApiPublicBotGuildPresenceRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordLoginRoute: ApiAuthDiscordLoginRoute,
  ApiPublicCronCosmeticRotationRoute: ApiPublicCronCosmeticRotationRoute,
  ApiPublicCronWeeklyRankingRoute: ApiPublicCronWeeklyRankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
