/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as AuthenticatedDashboardGuildIdRouteImport } from './routes/_authenticated/dashboard.$guildId'
import { Route as ApiAuthDiscordLoginRouteImport } from './routes/api/auth/discord/login'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'
import { Route as AuthenticatedDashboardGuildIdWelcomeRouteImport } from './routes/_authenticated/dashboard.$guildId.welcome'
import { Route as AuthenticatedDashboardGuildIdTicketsRouteImport } from './routes/_authenticated/dashboard.$guildId.tickets'
import { Route as AuthenticatedDashboardGuildIdReactionRolesRouteImport } from './routes/_authenticated/dashboard.$guildId.reaction-roles'
import { Route as AuthenticatedDashboardGuildIdModerationRouteImport } from './routes/_authenticated/dashboard.$guildId.moderation'
import { Route as AuthenticatedDashboardGuildIdLogsRouteImport } from './routes/_authenticated/dashboard.$guildId.logs'
import { Route as AuthenticatedDashboardGuildIdLevelingRouteImport } from './routes/_authenticated/dashboard.$guildId.leveling'
import { Route as AuthenticatedDashboardGuildIdEmbedsRouteImport } from './routes/_authenticated/dashboard.$guildId.embeds'
import { Route as AuthenticatedDashboardGuildIdEconomyRouteImport } from './routes/_authenticated/dashboard.$guildId.economy'
import { Route as AuthenticatedDashboardGuildIdCommandsRouteImport } from './routes/_authenticated/dashboard.$guildId.commands'
import { Route as AuthenticatedDashboardGuildIdAutoroleRouteImport } from './routes/_authenticated/dashboard.$guildId.autorole'
import { Route as AuthenticatedDashboardGuildIdAutomodRouteImport } from './routes/_authenticated/dashboard.$guildId.automod'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardGuildIdRoute =
  AuthenticatedDashboardGuildIdRouteImport.update({
    id: '/dashboard/$guildId',
    path: '/dashboard/$guildId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthDiscordLoginRoute = ApiAuthDiscordLoginRouteImport.update({
  id: '/api/auth/discord/login',
  path: '/api/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardGuildIdWelcomeRoute =
  AuthenticatedDashboardGuildIdWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdTicketsRoute =
  AuthenticatedDashboardGuildIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdReactionRolesRoute =
  AuthenticatedDashboardGuildIdReactionRolesRouteImport.update({
    id: '/reaction-roles',
    path: '/reaction-roles',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdModerationRoute =
  AuthenticatedDashboardGuildIdModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdLogsRoute =
  AuthenticatedDashboardGuildIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdLevelingRoute =
  AuthenticatedDashboardGuildIdLevelingRouteImport.update({
    id: '/leveling',
    path: '/leveling',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdEmbedsRoute =
  AuthenticatedDashboardGuildIdEmbedsRouteImport.update({
    id: '/embeds',
    path: '/embeds',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdEconomyRoute =
  AuthenticatedDashboardGuildIdEconomyRouteImport.update({
    id: '/economy',
    path: '/economy',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdCommandsRoute =
  AuthenticatedDashboardGuildIdCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdAutoroleRoute =
  AuthenticatedDashboardGuildIdAutoroleRouteImport.update({
    id: '/autorole',
    path: '/autorole',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)
const AuthenticatedDashboardGuildIdAutomodRoute =
  AuthenticatedDashboardGuildIdAutomodRouteImport.update({
    id: '/automod',
    path: '/automod',
    getParentRoute: () => AuthenticatedDashboardGuildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$guildId/automod': typeof AuthenticatedDashboardGuildIdAutomodRoute
  '/dashboard/$guildId/autorole': typeof AuthenticatedDashboardGuildIdAutoroleRoute
  '/dashboard/$guildId/commands': typeof AuthenticatedDashboardGuildIdCommandsRoute
  '/dashboard/$guildId/economy': typeof AuthenticatedDashboardGuildIdEconomyRoute
  '/dashboard/$guildId/embeds': typeof AuthenticatedDashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/leveling': typeof AuthenticatedDashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logs': typeof AuthenticatedDashboardGuildIdLogsRoute
  '/dashboard/$guildId/moderation': typeof AuthenticatedDashboardGuildIdModerationRoute
  '/dashboard/$guildId/reaction-roles': typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  '/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$guildId/automod': typeof AuthenticatedDashboardGuildIdAutomodRoute
  '/dashboard/$guildId/autorole': typeof AuthenticatedDashboardGuildIdAutoroleRoute
  '/dashboard/$guildId/commands': typeof AuthenticatedDashboardGuildIdCommandsRoute
  '/dashboard/$guildId/economy': typeof AuthenticatedDashboardGuildIdEconomyRoute
  '/dashboard/$guildId/embeds': typeof AuthenticatedDashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/leveling': typeof AuthenticatedDashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logs': typeof AuthenticatedDashboardGuildIdLogsRoute
  '/dashboard/$guildId/moderation': typeof AuthenticatedDashboardGuildIdModerationRoute
  '/dashboard/$guildId/reaction-roles': typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  '/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/$guildId/automod': typeof AuthenticatedDashboardGuildIdAutomodRoute
  '/_authenticated/dashboard/$guildId/autorole': typeof AuthenticatedDashboardGuildIdAutoroleRoute
  '/_authenticated/dashboard/$guildId/commands': typeof AuthenticatedDashboardGuildIdCommandsRoute
  '/_authenticated/dashboard/$guildId/economy': typeof AuthenticatedDashboardGuildIdEconomyRoute
  '/_authenticated/dashboard/$guildId/embeds': typeof AuthenticatedDashboardGuildIdEmbedsRoute
  '/_authenticated/dashboard/$guildId/leveling': typeof AuthenticatedDashboardGuildIdLevelingRoute
  '/_authenticated/dashboard/$guildId/logs': typeof AuthenticatedDashboardGuildIdLogsRoute
  '/_authenticated/dashboard/$guildId/moderation': typeof AuthenticatedDashboardGuildIdModerationRoute
  '/_authenticated/dashboard/$guildId/reaction-roles': typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  '/_authenticated/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/_authenticated/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/login': typeof ApiAuthDiscordLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/$guildId'
    | '/api/auth/logout'
    | '/dashboard/'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/autorole'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/economy'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logs'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/reaction-roles'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/welcome'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/$guildId'
    | '/api/auth/logout'
    | '/dashboard'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/autorole'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/economy'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logs'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/reaction-roles'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/welcome'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard/$guildId'
    | '/api/auth/logout'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/$guildId/automod'
    | '/_authenticated/dashboard/$guildId/autorole'
    | '/_authenticated/dashboard/$guildId/commands'
    | '/_authenticated/dashboard/$guildId/economy'
    | '/_authenticated/dashboard/$guildId/embeds'
    | '/_authenticated/dashboard/$guildId/leveling'
    | '/_authenticated/dashboard/$guildId/logs'
    | '/_authenticated/dashboard/$guildId/moderation'
    | '/_authenticated/dashboard/$guildId/reaction-roles'
    | '/_authenticated/dashboard/$guildId/tickets'
    | '/_authenticated/dashboard/$guildId/welcome'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordLoginRoute: typeof ApiAuthDiscordLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/$guildId': {
      id: '/_authenticated/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/discord/login': {
      id: '/api/auth/discord/login'
      path: '/api/auth/discord/login'
      fullPath: '/api/auth/discord/login'
      preLoaderRoute: typeof ApiAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/$guildId/welcome': {
      id: '/_authenticated/dashboard/$guildId/welcome'
      path: '/welcome'
      fullPath: '/dashboard/$guildId/welcome'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdWelcomeRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/tickets': {
      id: '/_authenticated/dashboard/$guildId/tickets'
      path: '/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdTicketsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/reaction-roles': {
      id: '/_authenticated/dashboard/$guildId/reaction-roles'
      path: '/reaction-roles'
      fullPath: '/dashboard/$guildId/reaction-roles'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdReactionRolesRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/moderation': {
      id: '/_authenticated/dashboard/$guildId/moderation'
      path: '/moderation'
      fullPath: '/dashboard/$guildId/moderation'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdModerationRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/logs': {
      id: '/_authenticated/dashboard/$guildId/logs'
      path: '/logs'
      fullPath: '/dashboard/$guildId/logs'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/leveling': {
      id: '/_authenticated/dashboard/$guildId/leveling'
      path: '/leveling'
      fullPath: '/dashboard/$guildId/leveling'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdLevelingRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/embeds': {
      id: '/_authenticated/dashboard/$guildId/embeds'
      path: '/embeds'
      fullPath: '/dashboard/$guildId/embeds'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdEmbedsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/economy': {
      id: '/_authenticated/dashboard/$guildId/economy'
      path: '/economy'
      fullPath: '/dashboard/$guildId/economy'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdEconomyRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/commands': {
      id: '/_authenticated/dashboard/$guildId/commands'
      path: '/commands'
      fullPath: '/dashboard/$guildId/commands'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdCommandsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/autorole': {
      id: '/_authenticated/dashboard/$guildId/autorole'
      path: '/autorole'
      fullPath: '/dashboard/$guildId/autorole'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdAutoroleRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
    '/_authenticated/dashboard/$guildId/automod': {
      id: '/_authenticated/dashboard/$guildId/automod'
      path: '/automod'
      fullPath: '/dashboard/$guildId/automod'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdAutomodRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRoute
    }
  }
}

interface AuthenticatedDashboardGuildIdRouteChildren {
  AuthenticatedDashboardGuildIdAutomodRoute: typeof AuthenticatedDashboardGuildIdAutomodRoute
  AuthenticatedDashboardGuildIdAutoroleRoute: typeof AuthenticatedDashboardGuildIdAutoroleRoute
  AuthenticatedDashboardGuildIdCommandsRoute: typeof AuthenticatedDashboardGuildIdCommandsRoute
  AuthenticatedDashboardGuildIdEconomyRoute: typeof AuthenticatedDashboardGuildIdEconomyRoute
  AuthenticatedDashboardGuildIdEmbedsRoute: typeof AuthenticatedDashboardGuildIdEmbedsRoute
  AuthenticatedDashboardGuildIdLevelingRoute: typeof AuthenticatedDashboardGuildIdLevelingRoute
  AuthenticatedDashboardGuildIdLogsRoute: typeof AuthenticatedDashboardGuildIdLogsRoute
  AuthenticatedDashboardGuildIdModerationRoute: typeof AuthenticatedDashboardGuildIdModerationRoute
  AuthenticatedDashboardGuildIdReactionRolesRoute: typeof AuthenticatedDashboardGuildIdReactionRolesRoute
  AuthenticatedDashboardGuildIdTicketsRoute: typeof AuthenticatedDashboardGuildIdTicketsRoute
  AuthenticatedDashboardGuildIdWelcomeRoute: typeof AuthenticatedDashboardGuildIdWelcomeRoute
}

const AuthenticatedDashboardGuildIdRouteChildren: AuthenticatedDashboardGuildIdRouteChildren =
  {
    AuthenticatedDashboardGuildIdAutomodRoute:
      AuthenticatedDashboardGuildIdAutomodRoute,
    AuthenticatedDashboardGuildIdAutoroleRoute:
      AuthenticatedDashboardGuildIdAutoroleRoute,
    AuthenticatedDashboardGuildIdCommandsRoute:
      AuthenticatedDashboardGuildIdCommandsRoute,
    AuthenticatedDashboardGuildIdEconomyRoute:
      AuthenticatedDashboardGuildIdEconomyRoute,
    AuthenticatedDashboardGuildIdEmbedsRoute:
      AuthenticatedDashboardGuildIdEmbedsRoute,
    AuthenticatedDashboardGuildIdLevelingRoute:
      AuthenticatedDashboardGuildIdLevelingRoute,
    AuthenticatedDashboardGuildIdLogsRoute:
      AuthenticatedDashboardGuildIdLogsRoute,
    AuthenticatedDashboardGuildIdModerationRoute:
      AuthenticatedDashboardGuildIdModerationRoute,
    AuthenticatedDashboardGuildIdReactionRolesRoute:
      AuthenticatedDashboardGuildIdReactionRolesRoute,
    AuthenticatedDashboardGuildIdTicketsRoute:
      AuthenticatedDashboardGuildIdTicketsRoute,
    AuthenticatedDashboardGuildIdWelcomeRoute:
      AuthenticatedDashboardGuildIdWelcomeRoute,
  }

const AuthenticatedDashboardGuildIdRouteWithChildren =
  AuthenticatedDashboardGuildIdRoute._addFileChildren(
    AuthenticatedDashboardGuildIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardGuildIdRoute: typeof AuthenticatedDashboardGuildIdRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardGuildIdRoute:
    AuthenticatedDashboardGuildIdRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordLoginRoute: ApiAuthDiscordLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
